# Generated by Django 5.1.3 on 2024-12-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_remove_user_username_user_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_code",
            field=models.CharField(
                blank="True",
                max_length=10,
                null="True",
                verbose_name="Verification_code",
            ),
            preserve_default="True",
        ),
    ]
