# Generated by Django 5.1.3 on 2024-11-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('created_at',), 'verbose_name': 'запись', 'verbose_name_plural': 'записи'},
        ),
    ]
