# Generated by Django 5.1.3 on 2024-12-02 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0005_alter_entry_options_entry_is_public"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="owner",
            field=models.ForeignKey(
                blank="True",
                null="True",
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
            preserve_default="True",
        ),
    ]
